export const SET_ALL = 'SET_ALL';
export const SET_RATES = 'SET_RATES';
export const SET_DEFAULT_CURRENCY = 'SET_DEFAULT_CURRENCY';
export const CURRENCY_FROM_CHANGE = 'CURRENCY_FROM_CHANGE';
export const CURRENCY_TO_CHANGE = 'CURRENCY_TO_CHANGE';
export const AMOUNT_FROM_CHANGE = 'AMOUNT_FROM_CHANGE';
export const AMOUNT_TO_CHANGE = 'AMOUNT_TO_CHANGE';
export const SET_TIMESTAMP = 'SET_TIMESTAMP';